var hierarchy =
[
    [ "LichessNET.Entities.Account.AccountPreferences", "classLichessNET_1_1Entities_1_1Account_1_1AccountPreferences.html", null ],
    [ "LichessNET.API.ApiRatelimitController", "classLichessNET_1_1API_1_1ApiRatelimitController.html", null ],
    [ "LichessNET.Entities.Tournament.Arena.ArenaPerf", "classLichessNET_1_1Entities_1_1Tournament_1_1Arena_1_1ArenaPerf.html", null ],
    [ "LichessNET.Entities.Tournament.Arena.ArenaTournament", "classLichessNET_1_1Entities_1_1Tournament_1_1Arena_1_1ArenaTournament.html", null ],
    [ "LichessNET.Entities.Account.Performance.BestWins", "classLichessNET_1_1Entities_1_1Account_1_1Performance_1_1BestWins.html", null ],
    [ "LichessNET.Entities.Social.Challenge", "classLichessNET_1_1Entities_1_1Social_1_1Challenge.html", null ],
    [ "LichessNET.Entities.Social.Challenger", "classLichessNET_1_1Entities_1_1Social_1_1Challenger.html", null ],
    [ "LichessNET.Entities.Social.ChallengeResponse", "classLichessNET_1_1Entities_1_1Social_1_1ChallengeResponse.html", null ],
    [ "LichessNET.Entities.Game.Clock", "classLichessNET_1_1Entities_1_1Game_1_1Clock.html", null ],
    [ "LichessNET.Entities.Account.Performance.Count", "classLichessNET_1_1Entities_1_1Account_1_1Performance_1_1Count.html", null ],
    [ "LichessNET.Entities.Social.CrossTable", "classLichessNET_1_1Entities_1_1Social_1_1CrossTable.html", null ],
    [ "LichessNET.Entities.Account.Performance.Cur", "classLichessNET_1_1Entities_1_1Account_1_1Performance_1_1Cur.html", null ],
    [ "LichessNET.Database.DatabaseClient", "classLichessNET_1_1Database_1_1DatabaseClient.html", null ],
    [ "LichessNET.Entities.Account.Performance.From", "classLichessNET_1_1Entities_1_1Account_1_1Performance_1_1From.html", null ],
    [ "LichessNET.Entities.Game.Game", "classLichessNET_1_1Entities_1_1Game_1_1Game.html", null ],
    [ "LichessNET.Entities.Stats.GameCounts", "classLichessNET_1_1Entities_1_1Stats_1_1GameCounts.html", null ],
    [ "LichessNET.Entities.Game.GamePlayer", "classLichessNET_1_1Entities_1_1Game_1_1GamePlayer.html", null ],
    [ "LichessNET.Entities.Game.GameStream", "classLichessNET_1_1Entities_1_1Game_1_1GameStream.html", null ],
    [ "LichessNET.Entities.Account.Performance.Glicko", "classLichessNET_1_1Entities_1_1Account_1_1Performance_1_1Glicko.html", null ],
    [ "LichessNET.Entities.Puzzle.Dashboard.GlobalPuzzlePerformance", "classLichessNET_1_1Entities_1_1Puzzle_1_1Dashboard_1_1GlobalPuzzlePerformance.html", null ],
    [ "LichessNET.Entities.Account.Performance.Highest", "classLichessNET_1_1Entities_1_1Account_1_1Performance_1_1Highest.html", null ],
    [ "LichessNET.Entities.Interfaces.IGameStats", "interfaceLichessNET_1_1Entities_1_1Interfaces_1_1IGameStats.html", [
      [ "LichessNET.Entities.Stats.GamemodeStats", "classLichessNET_1_1Entities_1_1Stats_1_1GamemodeStats.html", null ],
      [ "LichessNET.Entities.Stats.RunStats", "classLichessNET_1_1Entities_1_1Stats_1_1RunStats.html", null ]
    ] ],
    [ "JsonConverter", null, [
      [ "LichessNET.Converters.MillisecondUnixConverter", "classLichessNET_1_1Converters_1_1MillisecondUnixConverter.html", null ],
      [ "LichessNET.Converters.PermissionJsonConverter", "classLichessNET_1_1Converters_1_1PermissionJsonConverter.html", null ],
      [ "LichessNET.Converters.SecondsToTimeSpanConverter", "classLichessNET_1_1Converters_1_1SecondsToTimeSpanConverter.html", null ]
    ] ],
    [ "JsonConverter", null, [
      [ "LichessNET.Converters.GameStatsConverter", "classLichessNET_1_1Converters_1_1GameStatsConverter.html", null ]
    ] ],
    [ "LichessNET.API.LichessApiClient", "classLichessNET_1_1API_1_1LichessApiClient.html", null ],
    [ "LichessNET.Entities.Social.LichessProfile", "classLichessNET_1_1Entities_1_1Social_1_1LichessProfile.html", null ],
    [ "LichessNET.API.LichessStream", "classLichessNET_1_1API_1_1LichessStream.html", null ],
    [ "LichessNET.Entities.Teams.LichessTeam", "classLichessNET_1_1Entities_1_1Teams_1_1LichessTeam.html", null ],
    [ "LichessNET.Entities.Social.LichessUser", "classLichessNET_1_1Entities_1_1Social_1_1LichessUser.html", null ],
    [ "LichessNET.Entities.Social.Stream.LiveStreamer", "classLichessNET_1_1Entities_1_1Social_1_1Stream_1_1LiveStreamer.html", null ],
    [ "LichessNET.Entities.Social.Matchup", "classLichessNET_1_1Entities_1_1Social_1_1Matchup.html", null ],
    [ "LichessNET.Entities.Account.Performance.Max", "classLichessNET_1_1Entities_1_1Account_1_1Performance_1_1Max.html", null ],
    [ "LichessNET.Entities.Tournament.Arena.MinRatedGames", "classLichessNET_1_1Entities_1_1Tournament_1_1Arena_1_1MinRatedGames.html", null ],
    [ "LichessNET.Entities.Game.Move", "classLichessNET_1_1Entities_1_1Game_1_1Move.html", null ],
    [ "LichessNET.Entities.Game.MoveSequence", "classLichessNET_1_1Entities_1_1Game_1_1MoveSequence.html", null ],
    [ "LichessNET.Entities.Account.Performance.Nb", "classLichessNET_1_1Entities_1_1Account_1_1Performance_1_1Nb.html", null ],
    [ "LichessNET.Entities.Social.Note", "classLichessNET_1_1Entities_1_1Social_1_1Note.html", null ],
    [ "LichessNET.Entities.Game.OngoingGame", "classLichessNET_1_1Entities_1_1Game_1_1OngoingGame.html", null ],
    [ "LichessNET.Entities.Account.Performance.OpId", "classLichessNET_1_1Entities_1_1Account_1_1Performance_1_1OpId.html", null ],
    [ "LichessNET.Entities.Game.Opponent", "classLichessNET_1_1Entities_1_1Game_1_1Opponent.html", null ],
    [ "LichessNET.Entities.Account.Performance.Perf", "classLichessNET_1_1Entities_1_1Account_1_1Performance_1_1Perf.html", null ],
    [ "LichessNET.Entities.Account.Performance.PerformanceStats", "classLichessNET_1_1Entities_1_1Account_1_1Performance_1_1PerformanceStats.html", null ],
    [ "LichessNET.Entities.Account.Performance.PerfType", "classLichessNET_1_1Entities_1_1Account_1_1Performance_1_1PerfType.html", null ],
    [ "LichessNET.Entities.Account.Performance.PlayStreak", "classLichessNET_1_1Entities_1_1Account_1_1Performance_1_1PlayStreak.html", null ],
    [ "LichessNET.Entities.Stats.Playtime", "classLichessNET_1_1Entities_1_1Stats_1_1Playtime.html", null ],
    [ "LichessNET.Entities.Analysis.PositionEvaluation", "classLichessNET_1_1Entities_1_1Analysis_1_1PositionEvaluation.html", null ],
    [ "LichessNET.Entities.Account.Preferences", "classLichessNET_1_1Entities_1_1Account_1_1Preferences.html", null ],
    [ "LichessNET.Entities.Analysis.PrincipalVariation", "classLichessNET_1_1Entities_1_1Analysis_1_1PrincipalVariation.html", null ],
    [ "LichessNET.Entities.Puzzle.Puzzle", "classLichessNET_1_1Entities_1_1Puzzle_1_1Puzzle.html", null ],
    [ "LichessNET.Entities.Puzzle.Dashboard.PuzzleDashboard", "classLichessNET_1_1Entities_1_1Puzzle_1_1Dashboard_1_1PuzzleDashboard.html", null ],
    [ "LichessNET.Entities.Puzzle.PuzzleGame", "classLichessNET_1_1Entities_1_1Puzzle_1_1PuzzleGame.html", null ],
    [ "LichessNET.Entities.Puzzle.PuzzleRace", "classLichessNET_1_1Entities_1_1Puzzle_1_1PuzzleRace.html", null ],
    [ "LichessNET.Entities.Puzzle.Dashboard.PuzzleResults", "classLichessNET_1_1Entities_1_1Puzzle_1_1Dashboard_1_1PuzzleResults.html", null ],
    [ "LichessNET.Entities.Puzzle.Dashboard.PuzzleTheme", "classLichessNET_1_1Entities_1_1Puzzle_1_1Dashboard_1_1PuzzleTheme.html", null ],
    [ "LichessNET.Entities.Social.RatingDataPoint", "classLichessNET_1_1Entities_1_1Social_1_1RatingDataPoint.html", null ],
    [ "LichessNET.Entities.Account.Performance.Result", "classLichessNET_1_1Entities_1_1Account_1_1Performance_1_1Result.html", null ],
    [ "LichessNET.Entities.Account.Performance.ResultStreak", "classLichessNET_1_1Entities_1_1Account_1_1Performance_1_1ResultStreak.html", null ],
    [ "LichessNET.Entities.Tournament.Arena.Schedule", "classLichessNET_1_1Entities_1_1Tournament_1_1Arena_1_1Schedule.html", null ],
    [ "LichessNET.Entities.Account.Performance.Stat", "classLichessNET_1_1Entities_1_1Account_1_1Performance_1_1Stat.html", null ],
    [ "LichessNET.Entities.Puzzle.PuzzleStorm.StormDashboard", "classLichessNET_1_1Entities_1_1Puzzle_1_1PuzzleStorm_1_1StormDashboard.html", null ],
    [ "LichessNET.Entities.Puzzle.PuzzleStorm.StormDay", "classLichessNET_1_1Entities_1_1Puzzle_1_1PuzzleStorm_1_1StormDay.html", null ],
    [ "LichessNET.Entities.Puzzle.PuzzleStorm.StormHigh", "classLichessNET_1_1Entities_1_1Puzzle_1_1PuzzleStorm_1_1StormHigh.html", null ],
    [ "LichessNET.Entities.Account.Performance.Streak", "classLichessNET_1_1Entities_1_1Account_1_1Performance_1_1Streak.html", null ],
    [ "LichessNET.Entities.Social.Stream.Stream", "classLichessNET_1_1Entities_1_1Social_1_1Stream_1_1Stream.html", null ],
    [ "LichessNET.Entities.Social.Stream.Streamer", "classLichessNET_1_1Entities_1_1Social_1_1Stream_1_1Streamer.html", null ],
    [ "LichessNET.Entities.Social.StreamingInfo", "classLichessNET_1_1Entities_1_1Social_1_1StreamingInfo.html", null ],
    [ "LichessNET.Entities.Tournament.SwissTournament", "classLichessNET_1_1Entities_1_1Tournament_1_1SwissTournament.html", null ],
    [ "LichessNET.Entities.Tournament.SwissTournamentStats", "classLichessNET_1_1Entities_1_1Tournament_1_1SwissTournamentStats.html", null ],
    [ "LichessNET.Entities.Analysis.TablebaseLookup", "classLichessNET_1_1Entities_1_1Analysis_1_1TablebaseLookup.html", null ],
    [ "LichessNET.Entities.Analysis.TablebaseMove", "classLichessNET_1_1Entities_1_1Analysis_1_1TablebaseMove.html", null ],
    [ "LichessNET.Entities.Social.TeamLeader", "classLichessNET_1_1Entities_1_1Social_1_1TeamLeader.html", null ],
    [ "LichessNET.Entities.Teams.TeamMember", "classLichessNET_1_1Entities_1_1Teams_1_1TeamMember.html", null ],
    [ "LichessNET.Entities.Account.Performance.Time", "classLichessNET_1_1Entities_1_1Account_1_1Performance_1_1Time.html", null ],
    [ "LichessNET.Entities.Game.TimeControl", "classLichessNET_1_1Entities_1_1Game_1_1TimeControl.html", null ],
    [ "LichessNET.Entities.Social.Timeline.Timeline", "classLichessNET_1_1Entities_1_1Social_1_1Timeline_1_1Timeline.html", null ],
    [ "LichessNET.Entities.Social.Timeline.TimelineEntry", "classLichessNET_1_1Entities_1_1Social_1_1Timeline_1_1TimelineEntry.html", null ],
    [ "LichessNET.Entities.Social.Timeline.TimelineEventData", "classLichessNET_1_1Entities_1_1Social_1_1Timeline_1_1TimelineEventData.html", [
      [ "LichessNET.Entities.Social.Timeline.BlogPostEventData", "classLichessNET_1_1Entities_1_1Social_1_1Timeline_1_1BlogPostEventData.html", null ],
      [ "LichessNET.Entities.Social.Timeline.FollowEventData", "classLichessNET_1_1Entities_1_1Social_1_1Timeline_1_1FollowEventData.html", null ],
      [ "LichessNET.Entities.Social.Timeline.ForumPostEventData", "classLichessNET_1_1Entities_1_1Social_1_1Timeline_1_1ForumPostEventData.html", null ],
      [ "LichessNET.Entities.Social.Timeline.GameEndEventData", "classLichessNET_1_1Entities_1_1Social_1_1Timeline_1_1GameEndEventData.html", null ],
      [ "LichessNET.Entities.Social.Timeline.PlanRenewEventData", "classLichessNET_1_1Entities_1_1Social_1_1Timeline_1_1PlanRenewEventData.html", null ],
      [ "LichessNET.Entities.Social.Timeline.PlanStartEventData", "classLichessNET_1_1Entities_1_1Social_1_1Timeline_1_1PlanStartEventData.html", null ],
      [ "LichessNET.Entities.Social.Timeline.SimulCreateEventData", "classLichessNET_1_1Entities_1_1Social_1_1Timeline_1_1SimulCreateEventData.html", null ],
      [ "LichessNET.Entities.Social.Timeline.SimulJoinEventData", "classLichessNET_1_1Entities_1_1Social_1_1Timeline_1_1SimulJoinEventData.html", null ],
      [ "LichessNET.Entities.Social.Timeline.StreamStartEventData", "classLichessNET_1_1Entities_1_1Social_1_1Timeline_1_1StreamStartEventData.html", null ],
      [ "LichessNET.Entities.Social.Timeline.StudyLikeEventData", "classLichessNET_1_1Entities_1_1Social_1_1Timeline_1_1StudyLikeEventData.html", null ],
      [ "LichessNET.Entities.Social.Timeline.TeamCreateEventData", "classLichessNET_1_1Entities_1_1Social_1_1Timeline_1_1TeamCreateEventData.html", null ],
      [ "LichessNET.Entities.Social.Timeline.TeamJoinEventData", "classLichessNET_1_1Entities_1_1Social_1_1Timeline_1_1TeamJoinEventData.html", null ],
      [ "LichessNET.Entities.Social.Timeline.TourJoinEventData", "classLichessNET_1_1Entities_1_1Social_1_1Timeline_1_1TourJoinEventData.html", null ],
      [ "LichessNET.Entities.Social.Timeline.UblogPostEventData", "classLichessNET_1_1Entities_1_1Social_1_1Timeline_1_1UblogPostEventData.html", null ],
      [ "LichessNET.Entities.Social.Timeline.UblogPostLikeEventData", "classLichessNET_1_1Entities_1_1Social_1_1Timeline_1_1UblogPostLikeEventData.html", null ],
      [ "LichessNET.Entities.Social.Timeline.UnknownEventData", "classLichessNET_1_1Entities_1_1Social_1_1Timeline_1_1UnknownEventData.html", null ]
    ] ],
    [ "LichessNET.Entities.Social.Timeline.TimelineUser", "classLichessNET_1_1Entities_1_1Social_1_1Timeline_1_1TimelineUser.html", null ],
    [ "LichessNET.Entities.Account.Performance.To", "classLichessNET_1_1Entities_1_1Account_1_1Performance_1_1To.html", null ],
    [ "LichessNET.Entities.OAuth.TokenInfo", "classLichessNET_1_1Entities_1_1OAuth_1_1TokenInfo.html", null ],
    [ "LichessNET.Entities.Account.Performance.UserId", "classLichessNET_1_1Entities_1_1Account_1_1Performance_1_1UserId.html", null ],
    [ "LichessNET.Entities.Social.UserOverview", "classLichessNET_1_1Entities_1_1Social_1_1UserOverview.html", null ],
    [ "LichessNET.Entities.Social.UserRealTimeStatus", "classLichessNET_1_1Entities_1_1Social_1_1UserRealTimeStatus.html", null ],
    [ "LichessNET.Entities.Game.Variant", "classLichessNET_1_1Entities_1_1Game_1_1Variant.html", null ],
    [ "LichessNET.Entities.Tournament.VerdictEntity", "classLichessNET_1_1Entities_1_1Tournament_1_1VerdictEntity.html", null ],
    [ "LichessNET.Entities.Tournament.Verdicts", "classLichessNET_1_1Entities_1_1Tournament_1_1Verdicts.html", null ],
    [ "LichessNET.Entities.Account.Performance.WorstLosses", "classLichessNET_1_1Entities_1_1Account_1_1Performance_1_1WorstLosses.html", null ]
];